Add FSI section to Input File docs.
Exawind/nalu-wind pull request #1220
Opened 2023-10-10 23:00 UTC by neilmatula

2023-10-11 05:59 UTC, psakievich requested changes
Looks good. Thanks for typing all this up. Requesting a few edits.

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   List of strings (in double quotes) indicating the mesh element blocks
Double quotes are not required for yaml to recognize strings.  Raw characters are fine.

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   provided by AeroDyn and the true CFD loads provided by Nalu-Wind.
```suggestion
   provided by AeroDyn and the true CFD loads provided by Nalu-Wind during startup to help with stability while the CFD flow field develops around the turbine structure.
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   where :math:`\phi` is the angle that the turbine has rotated through,
```suggestion
   where :math:`\phi` is the angle that the turbine has rotated through (including any initial OpenFAST runs),
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   :math:`\phi_\text{delta}` is the value of ``az_blend_delta``.
```suggestion
Definition supplied in the `turbine_name.az_blend_mean` parameter's description.
```
No need to repeat ourselves here 😎

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   ramping of blade deflections applied in Nalu.  The temporal ramping enables a smooth
```suggestion
   ramping of blade deflections applied in Nalu-Wind.  The temporal ramping enables a smooth
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   transition from the reference configuration to the full deflections, and
```suggestion
   transition for the blades from a rigid body motion based on the hub motion to the full blade deflections, and
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   improves the stability of the simulation.  The span ramping enables the root section
```suggestion
   improves the stability of the simulation during startup.  The span ramping enables the root section
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   Prior to this time, zero deflections will be provided.  Note that this
```suggestion
   Prior to this time, zero blade deflections will be provided.  Note that this
```

2023-10-11 05:59 UTC, psakievich commented on docs/source/user/nalu_run/nalu_inp.rst
> +   After this time, full deflections will be provided.  Note that this
```suggestion
   After this time, full blade deflections will be provided.  Note that this
```

2023-10-11 06:01 UTC, psakievich commented
Middle equation, I believe it should be `\theta-\theta_0` in the numerator.

2023-10-11 21:37 UTC, neilmatula commented
@psakievich 
Theta is measured from the top blade in that figure, right?
If it's theta-theta0 in the blue (ramped) region, that would be a negative number.
Unless I've got it totally wrong

2023-10-11 21:53 UTC, psakievich commented
> @psakievich Theta is measured from the top blade in that figure, right? If it's theta-theta0 in the blue (ramped) region, that would be a negative number. Unless I've got it totally wrong

Ah yeah you are right.

2023-10-13 15:33 UTC, psakievich approved these changes

2023-10-16 15:59 UTC, merged