No slip
Exawind/nalu-wind pull request #806
Opened 2021-02-18 22:51 UTC by neilmatula

**Pull-request type:**
- [ ] Bug fix 
- [ ] Documentation update
- [ ] Feature enhancement

## Description of the pull-request

*Provide a description of your proposed changes. If there is a related issue, please specify.**

## Checklist

**NOTE** The checklist below is a suggestion and not mandatory. You don't have
to _check all boxes_ to submit a pull request. However, please add a brief
explanation in your pull request summary explaining the omission for the benefit
of reviewers and developers.

*All pull requests*
- [ ] Builds successfully (*must test on at least one system/compiler combination*)
  - Operating systems 
    - [ ] Linux
    - [ ] MacOS
  - Compilers 
    - [ ] GCC
    - [ ] LLVM/Clang
    - [ ] Intel compilers
    - [ ] NVIDIA CUDA
- [ ] Compiles without warnings
- [ ] Passes all unit tests
- [ ] Passes all regression tests
- [ ] Documentation builds without errors

*For new code updates*
- [ ] Documentation updates - additions to user, theory, and verification manuals
- [ ] New unit tests providing coverage for new code, bug fixes etc.
- [ ] New regression tests exercising the new code

2021-02-19 00:17 UTC, rcknaus commented on src/LowMachEquationSystem.C
> +          ablWallNodeMask_.reset(new MomentumABLWallFuncMaskUtil(realm_, part));
Need to add the part to the existing mask utility if it exists. This will just operate on the last part in the no slip wall function is applied to.

2021-02-19 00:20 UTC, rcknaus commented on src/edge_kernels/MomentumABLWallFuncMaskUtil.C
> +  for (const auto* ib : buckets) {
Probably should just make this operate on device.  Should be pretty straightfoward.

2021-02-19 00:24 UTC, rcknaus commented on reg_tests/test_files/ablNeutralEdgeNoSlip/ablNeutralEdgeNoSlip.log
> +===============================================================================
Don't include the log file

2021-02-19 00:25 UTC, rcknaus requested changes
Looks good to me overall.  A couple changes though.

2021-02-19 18:02 UTC, sayerhs requested changes

2021-02-19 18:04 UTC, sayerhs commented
@neilmatula requesting changes because of unit-test failure, and to make sure that the masking field works as expected on GPU regression tests.

2021-02-19 18:16 UTC, psakievich commented on reg_tests/test_files/ablNeutralEdgeNoSlip/nalu_abl_mesh.yaml
> +nalu_abl_mesh:
It's not needed.  We can remove it.  This is just a copy of the ablNeutralEdge regression test so the file exists there as well.

2021-02-19 18:17 UTC, psakievich commented on reg_tests/test_files/ablNeutralEdgeNoSlip/nalu_preprocess.yaml
> +# -*- mode: yaml -*-
no we can remove this as well

2021-02-24 15:44 UTC, psakievich commented
Closing PR due to #810

2021-02-24 15:44 UTC, closed without merging